export interface AlertThreshold {
  id: string;
  type: 'low_stock' | 'out_of_stock' | 'overstocked' | 'expired';
  name: string;
  description: string;
  enabled: boolean;
  threshold: number; // percentage for stock alerts (e.g., 30 = 30%)
  severity: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  conditions: {
    checkPercentage: boolean;
    checkAbsolute: boolean;
    absoluteValue?: number;
  };
}

export interface AlertSettings {
  id: string;
  userId?: string; // null for global settings
  role: 'user' | 'admin' | 'superadmin';
  thresholds: AlertThreshold[];
  notifications: {
    email: boolean;
    inApp: boolean;
    sound: boolean;
  };
  autoAcknowledge: {
    enabled: boolean;
    afterHours: number;
  };
  createdAt: Date;
  updatedAt: Date;
}

export interface AutoAlert {
  id: string;
  productId: string;
  productName: string;
  productCode: string;
  type: 'low_stock' | 'out_of_stock' | 'overstocked' | 'expired';
  severity: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  message: string;
  currentStock: number;
  totalStock: number;
  percentage: number;
  threshold: number;
  thresholdId: string;
  acknowledged: boolean;
  acknowledgedBy?: string;
  acknowledgedAt?: Date;
  timestamp: Date;
  autoGenerated: boolean;
}